[package]
name = "extractor"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { version = "3.2.25", features = ["derive"] }
reqwest = { version = "0.11.18", features = [
    "blocking",
    "rustls-tls",
], default-features = false }
rustc-hash = "1.1.0"
zstd = "0.12.3"
